# ComfyUI-StalkerVr Configuration

llm:
  system_prompts_path: "data/llm/system_instruction"
  presets_path: "data/llm/presets"

# Enable global loging (for develop)
logging:
  global_enabled: true

  # Control logging for specific node classes here
  node_settings:
    WanVideoLoraCivitAIDownloader: true
    WanVideoLoraPairCreator: true
    WanVideoLoraPairSelect: false
    WanVideoEnhanceMotionAdvancedKJ: true
    WanVideoEnhanceMotionAdvanced: true
    LoraLoaderExtended: false
    LoraLoaderExtendedBatch: false

    JsonFieldValueExtractor: false
    JsonFieldRemover: false
    JsonFieldReplaceExtend: false
    JsonPromptToTextPromptConverter: false
    JsonSerializeObject: false
    JsonDeserializeObject: false
    JsonFormat: false
    JsonMinify: false
    JsonPathLoader: false
    JsonBuilder: false
    JsonPairInput: false

    StringBuilder: false
    StringWrapper: false
    StringNormalize: false

    ImageGridCropper: false
    ImageCropper: false
    ImageRatioResizer: false
    ImageGetSize: false
    ImageDesiredResolution: false
    ImagesLoadWithMetadata: false
    ImageLoadWithMetadata: false
    ImageSaveWithMetadata: false

    CurrentDateTime: false
    FormatDatePath: false
    FileSavePath: false
    SaveTextFile: false

    YAMLLoadPrompt: false
    YAMLSavePrompt: false

    ImageWatermark: false
    TextWatermark: false
    GenerateCreationTime: false
    SaveVideoWithMetadata: false

    LlamaCppTextGenerator: true
