# ComfyUI-StalkerVr Configuration

llm:
  system_prompts_path:
    - "data/llm/system_instruction"                         # от корня РАСШИРЕНИЯ (данные расширения)
    - "/home/stalkervr/Documents/ComfyUI/LLM-Prompts/test"  # только хост
  presets_path:
    - "data/llm/presets"                                    # от корня РАСШИРЕНИЯ
    - "/home/stalkervr/Documents/ComfyUI/LLM-Model-Presets" # только хост
  models_path:
    - "models/LLM"                                          # от корня ComfyUI — работает ВЕЗДЕ
    - "/home/stalkervr/.lmstudio/models"                    # только хост

# Enable loging (for develop)
logging:
  node_class:
    LlamaCppTextGenerator: true   # ← лог выводится
    LoraApply: true
    LoraApplyModelOnly: true
    LlamaPresetLoader: true
    WanVideoEnhanceMotionAdvancedKJ: true
