# ComfyUI-StalkerVr Configuration

llm:
  system_prompts_path:
    - "data/llm/system_instruction"              # Основной каталог расширения
    - "/home/stalkervr/Documents/llm_prompts"    # Личная коллекция
  presets_path:
    - "data/llm/presets"                         # Основной каталог расширения
    - "/home/stalkervr/Documents/llm_presets"    # Личная коллекция
  models_path:
    - "/mnt/ai/ComfyUI/models/LLM"           # ComfyUI каталог LLM моделей
    - "/home/stalkervr/.lmstudio/models"     # каталог LM Studio моделей

# Enable loging (for develop)
logging:
  node_class:
    LlamaCppTextGenerator: true   # ← лог выводится
    LoraApply: true
    LoraApplyModelOnly: true
    LlamaPresetLoader: true
